name: lsfusion

volumes:
  lx_postgres_data: {}
  lx_server_data: {}
  lx_client_data: {}

services:
  db:
    image: postgres:latest
    container_name: lx_postgres
    volumes:
      - lx_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - ./.envs_example/db

  server:
    build:
      context: .
      dockerfile: ./compose/server/Dockerfile
    container_name: lx_server
    depends_on:
      - db
    volumes:
      - lx_server_data:/lsfusion
    env_file:
      - ./.envs_example/server

  client:
    image: lsfusion/client:6.0
    container_name: lx_client
    depends_on:
      - server
    volumes:
      - lx_client_data:/usr/local/tomcat/conf/Catalina
    ports:
      - "8080:8080"
    env_file:
      - ./.envs_example/client
